# Generated by Django 4.0.4 on 2022-05-02 16:16

import carepackage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicplayer', '0006_musictrack_reviews_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='carepack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(blank=True, max_length=30, null=True, validators=[carepackage.models.validate_string], verbose_name='Pack name')),
                ('pack_desc', models.TextField(blank=True, max_length=100, null=True, verbose_name='Pack Description')),
                ('pack_image', models.ImageField(blank=True, default='packcoverDB/default.png', null=True, upload_to='packcoverDB/')),
                ('subscribed_count', models.IntegerField(blank=True, default=0, null=True)),
                ('pack_pdf', models.FileField(blank=True, default='packpdfDB/default.png', null=True, upload_to='packpdfDB/')),
                ('uploaded_date', models.DateField(auto_now_add=True, verbose_name='Uploaded date')),
                ('pack_tracks', models.ManyToManyField(blank=True, default=None, related_name='packtracks', to='musicplayer.musictrack')),
                ('uploaded_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
        ),
        migrations.CreateModel(
            name='therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfirstname', models.CharField(blank=True, max_length=30, null=True, validators=[carepackage.models.validate_string], verbose_name='FirstName')),
                ('tlastname', models.CharField(blank=True, max_length=30, null=True, validators=[carepackage.models.validate_string], verbose_name='LastName')),
                ('tdob', models.DateField(blank=True, null=True, validators=[carepackage.models.validate_dob], verbose_name='Date of Birth')),
                ('tgender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'others')], max_length=7, null=True, verbose_name='Gender')),
                ('tmobile', models.CharField(blank=True, max_length=10, null=True, validators=[carepackage.models.validate_mobile], verbose_name='Mobile number')),
                ('temail', models.EmailField(blank=True, max_length=254, null=True)),
                ('tcountry', models.CharField(default='INDIA', max_length=20, verbose_name='Country')),
                ('timage', models.ImageField(blank=True, default='therapistDB/default.png', null=True, upload_to='therapistDB/')),
                ('tlicense', models.CharField(default='0001', max_length=20, verbose_name='Licence number')),
            ],
        ),
        migrations.CreateModel(
            name='packsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_date', models.DateField(auto_now_add=True, verbose_name='Subscribed date')),
                ('completed', models.BooleanField(default=False, verbose_name='Pack completed')),
                ('pack_subscribed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carepackage.carepack', verbose_name='Pack subscribed')),
                ('suser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
