# Generated by Django 4.0.4 on 2022-05-03 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carepackage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carepack',
            name='prepared_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='carepackage.therapist', verbose_name='Therapist'),
        ),
    ]
