# Generated by Django 4.0.4 on 2022-04-21 19:23

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GUprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=30, null=True, validators=[accounts.models.validate_string], verbose_name='FirstName')),
                ('lastname', models.CharField(blank=True, max_length=30, null=True, validators=[accounts.models.validate_string], verbose_name='LastName')),
                ('dob', models.DateField(blank=True, null=True, validators=[accounts.models.validate_dob], verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'others')], max_length=7, null=True, verbose_name='Gender')),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, validators=[accounts.models.validate_mobile], verbose_name='Mobile number')),
                ('country', models.CharField(choices=[('INDIA', 'INDIA')], default='INDIA', max_length=20, verbose_name='Country')),
                ('image', models.ImageField(blank=True, default='guprofileDB/default.png', null=True, upload_to='guprofileDB/')),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('guOTP', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
