# Generated by Django 4.0.4 on 2022-04-30 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0003_category_cat_score_playlist_category_fk_and_more'),
        ('accounts', '0002_guprofile_like_count_guprofile_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='guprofile',
            name='current_mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicplayer.category', verbose_name='current mood'),
        ),
    ]
