# Generated by Django 4.0.4 on 2022-04-28 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import musicplayer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=30, null=True, validators=[musicplayer.models.validate_string], verbose_name='category name')),
                ('category_desc', models.TextField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='musictrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=30, validators=[musicplayer.models.validate_string], verbose_name='Track name')),
                ('track_path', models.FileField(upload_to='musicDB/', verbose_name='Track path')),
                ('duration', models.IntegerField(blank=True, default=0, verbose_name='Track duration')),
                ('cover_image', models.ImageField(default='musiccoverDB/defaultcover.jpg', upload_to='musiccoverDB/', verbose_name='Track image')),
                ('uploaded_date', models.DateField(auto_now_add=True, verbose_name='Uploaded date')),
                ('likes', models.FloatField(blank=True, default=0.0, verbose_name='ratings')),
                ('category_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='musicplayer.category', verbose_name='category')),
                ('uploaded_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
        ),
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=30, validators=[musicplayer.models.validate_string], verbose_name='Playlist name')),
                ('uploaded_date', models.DateField(auto_now_add=True, verbose_name='Uploaded date')),
                ('uploaded_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
        ),
        migrations.CreateModel(
            name='playlist_song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.playlist', verbose_name='playlist name')),
                ('track_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.musictrack', verbose_name='track name')),
            ],
        ),
        migrations.CreateModel(
            name='music_reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(max_length=200, verbose_name='Review')),
                ('reviewed_date', models.DateField(auto_now_add=True, verbose_name='Review date')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('track_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.musictrack', verbose_name='track name')),
            ],
        ),
    ]
