# Generated by Django 4.0.4 on 2022-04-29 06:14

from django.db import migrations, models
import musicplayer.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200, verbose_name='Question')),
                ('score', models.IntegerField(blank=True, default=0, verbose_name='score for true')),
            ],
        ),
        migrations.RemoveField(
            model_name='musictrack',
            name='likes',
        ),
        migrations.AddField(
            model_name='musictrack',
            name='likes_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Likes count'),
        ),
        migrations.AddField(
            model_name='musictrack',
            name='track_creator',
            field=models.CharField(default='Ananymous', max_length=30, validators=[musicplayer.models.validate_string], verbose_name='Track creator'),
        ),
    ]
