# Generated by Django 4.0.4 on 2022-04-29 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0002_questionnaire_remove_musictrack_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Score'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='category_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicplayer.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='score',
            field=models.IntegerField(blank=True, default=1, verbose_name='score for true'),
        ),
    ]
