# Generated by Django 4.0.4 on 2022-05-02 03:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicplayer', '0003_category_cat_score_playlist_category_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
