# Generated by Django 4.0.4 on 2022-05-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0004_musictrack_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musictrack',
            name='category_id',
        ),
        migrations.AddField(
            model_name='playlist',
            name='musictracks',
            field=models.ManyToManyField(blank=True, default=None, related_name='musictracks', to='musicplayer.musictrack'),
        ),
    ]
