# Generated by Django 4.0.4 on 2022-05-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0005_remove_musictrack_category_id_playlist_musictracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='reviews_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Reviews count'),
        ),
    ]
