# Generated by Django 4.0.4 on 2022-05-06 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicplayer', '0006_musictrack_reviews_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='music_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=600, verbose_name='Review')),
                ('reviewed_date', models.DateField(auto_now_add=True, verbose_name='Reviewed date')),
                ('reviewed_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
        ),
    ]
