# Generated by Django 4.0.4 on 2022-05-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0007_music_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_review',
            name='review_track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicplayer.musictrack', verbose_name='Reviewd track'),
        ),
    ]
