# Generated by Django 4.0.4 on 2022-05-06 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicplayer', '0008_music_review_review_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_reviews',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AlterField(
            model_name='music_reviews',
            name='track_fk',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='musicplayer.musictrack', verbose_name='track name'),
        ),
    ]
