# Generated by Django 4.0.4 on 2022-05-08 11:55

from django.db import migrations, models
import musicplayer.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0009_alter_music_reviews_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictrack',
            name='track_path',
            field=models.FileField(upload_to='musicDB/', validators=[musicplayer.models.validate_is_audio], verbose_name='Track path'),
        ),
    ]
