# Generated by Django 4.0.4 on 2022-05-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0010_alter_musictrack_track_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictrack',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Track duration'),
        ),
    ]
