# Generated by Django 4.0.4 on 2022-05-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0011_alter_musictrack_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(default='musiccoverDB/defaultcover.jpg', upload_to='musiccoverDB/', verbose_name='Playlist cover'),
        ),
    ]
